<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 7/28/17
 * Time: 5:27 PM
 */
namespace yuanshuai\yscomponents\tencent\video;
use yuanshuai\yscomponents\extension\helpers\ArrayHelper;
use yuanshuai\yscomponents\tencent\TencentComponent;

/**
 * Class Video
 * @package yuanshuai\yscomponents\tencent\video
 */
class Video extends TencentComponent
{
    const VOD_LIST = "DescribeVodInfo";
    const VOD_INFO = "GetVideoInfo";

    const PAGE_SIZE = 10;
    public function init()
    {
        $this->module = \QcloudApi::MODULE_VOD;
        $this->method = "GET";
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 批量获取视频信息
     */
    public function vodlist($data = [])
    {
        $params = [
            "status"=>ArrayHelper::getValue($data,"status",2),
            "orderby"=>ArrayHelper::getValue($data,"orderby",1),
            "pageNo"=>ArrayHelper::getValue($data,"page",1),
            "pageSize"=>ArrayHelper::getValue($data,"pageSize",static::PAGE_SIZE)
        ];
        return $this->request(static::VOD_LIST,$params);
    }

    public function vodinfo($fileId)
    {
        $params = [
            "fileId"=>$fileId
        ];
        return $this->request(static::VOD_INFO,$params);
    }
}