<?php
/**
 * Created by PhpStorm.
 * User: helong
 * Date: 2017/3/28
 * Time: 18:23
 */

namespace yuanshuai\yscomponents;
use Yii;


use yii\base\Component;
use yii\helpers\Json;
use yuanshuai\yscomponents\server\Server;

class ServerComponent extends Component
{
    use SwooleTrait;
    public $config = [
        'host'=>ConstHelper::CONFIG_HOST,
        'port'=>ConstHelper::CONFIG_PORT,
        'pidfile'=>ConstHelper::CONFIG_PID_FILE,
        'client_timeout'=>ConstHelper::CONFIG_CLIENT_TIMEOUT,
        'setting'=>[
            'process_name'=>ConstHelper::CONFIG_PROCESS_NAME,
            'worker_num'=>8,
            'task_worker_num'=>4,
            'daemonize'=>true,
        ],
    ];
    private $server;
    public function init()
    {
        if (!isset($this->config['setting']['log_file'])){
            $this->config['setting']['log_file'] = Yii::getAlias("@app/runtime/logs/swoole.log");
        }
        $this->check();
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function start(){
        $this->show("服务开始启动。。。。");
        $pidfile = $this->config['pidfile'];
        $host = $this->config['host'];
        $port = $this->config['port'];
        if (file_exists($pidfile)){
            $pid = explode('-',file_get_contents($pidfile));
            exec("ps ax | awk '{print $1}' | grep -e {$pid[0]}",$out);
            if (!empty($out)){
                $this->show("服务已启动，进程ID为:{$pid[0]}",true);
            } else {
                unlink($pidfile);
            }
        }

        //检测端口占用
        $bind = $this->checkPort($port);
        foreach ($bind as $item){
            if ($item['ip'] == '*' || $item['ip'] == 'localhost' ||  $item['ip'] == $host) {
                $this->show("{$port}端口已经被占用",true);
            }
        }

        $this->show("服务启动成功");
        $this->server = new Server($this->config);
        $this->server->start();
    }
}