<?php
/**
 * Created by PhpStorm.
 * User: helong
 * Date: 2017/7/19
 * Time: 下午11:47
 */

namespace yuanshuai\yscomponents\extension\actions;


use yuanshuai\yscomponents\extension\FileHelper;

class UploadFileAction extends BaseAction
{
    protected $fileField = "file";
    public $module = 'file';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ($this->request->get("fileparam")) {
            $this->fileField = $this->request->get("fileparam");
        }
    }

    public function run()
    {
        FileHelper::$module = $this->module;
        FileHelper::$filePath = "/upload/{:module}/{:Y}-{:M}-{:D}/{:name}.{:ext}";
        $result = FileHelper::upload($this->fileField);
        if (!$result) {
            return $this->controller->error("上传失败",Response::FORMAT_JSON);
        }
        $data = [
            "files"=>[
                [
                    "name"=>$result["filename"],
                    "size"=>$result["filesize"],
                    "type"=>$result["filetype"],
                    "path"=>$result["filepath"],
                    "url"=>$result["fileurl"],
                    "base_url"=>\Yii::getAlias(FileHelper::$cdnDomain)
                ]
            ]
        ];
        return $this->controller->asJson($data);
    }
}